/**
 * SuburbMates V1.1 - Database Types
 * Auto-generated types for Supabase tables
 * This file would normally be generated by: supabase gen types typescript
 */

export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          email: string;
          first_name: string | null;
          last_name: string | null;
          user_type: 'customer' | 'business_owner' | 'admin';
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
          created_as_business_owner_at: string | null;
        };
        Insert: Omit<Database['public']['Tables']['users']['Row'], 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['users']['Insert']>;
      };
      vendors: {
        Row: {
          id: string;
          user_id: string;
          business_name: string;
          abn: string | null;
          abn_verified: boolean;
          abn_verified_at: string | null;
          tier: 'none' | 'basic' | 'pro' | 'suspended';
          is_vendor: boolean;
          vendor_status: 'inactive' | 'active' | 'suspended';
          can_sell_products: boolean;
          stripe_account_id: string | null;
          stripe_account_status: string | null;
          stripe_onboarding_complete: boolean;
          product_quota: number;
          storage_quota_gb: number;
          commission_rate: number;
          bio: string | null;
          primary_lga_id: number | null;
          logo_url: string | null;
          product_count: number;
          storage_used_mb: number;
          suspension_reason: string | null;
          suspended_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['vendors']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['vendors']['Insert']>;
      };
      products: {
        Row: {
          id: string;
          vendor_id: string;
          category_id: number;
          lga_id: number | null;
          title: string;
          slug: string;
          description: string | null;
          price: number;
          digital_file_url: string | null;
          file_size_bytes: number | null;
          thumbnail_url: string | null;
          published: boolean;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: Omit<Database['public']['Tables']['products']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['products']['Insert']>;
      };
      orders: {
        Row: {
          id: string;
          customer_id: string;
          vendor_id: string;
          product_id: string;
          total_amount: number;
          commission_amount: number;
          vendor_amount: number;
          stripe_payment_intent_id: string;
          stripe_charge_id: string | null;
          status: 'pending' | 'succeeded' | 'failed' | 'reversed';
          download_url: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['orders']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['orders']['Insert']>;
      };
      lgas: {
        Row: {
          id: number;
          name: string;
          council_abbreviation: string | null;
          featured_slot_cap: number;
          active: boolean;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['lgas']['Row'], 'id' | 'created_at'>;
        Update: Partial<Database['public']['Tables']['lgas']['Insert']>;
      };
      categories: {
        Row: {
          id: number;
          name: string;
          slug: string;
          description: string | null;
          active: boolean;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['categories']['Row'], 'id' | 'created_at'>;
        Update: Partial<Database['public']['Tables']['categories']['Insert']>;
      };
      refund_requests: {
        Row: {
          id: string;
          order_id: string;
          customer_id: string;
          vendor_id: string;
          reason: string;
          description: string | null;
          amount: number;
          status: 'pending' | 'approved' | 'rejected' | 'cancelled';
          vendor_response: string | null;
          resolved_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['refund_requests']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['refund_requests']['Insert']>;
      };
      disputes: {
        Row: {
          id: string;
          order_id: string;
          customer_id: string;
          vendor_id: string;
          refund_request_id: string | null;
          reason: string;
          status: 'open' | 'under_review' | 'resolved' | 'closed' | 'escalated';
          admin_notes: string | null;
          resolution: string | null;
          resolved_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['disputes']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['disputes']['Insert']>;
      };
      appeals: {
        Row: {
          id: string;
          vendor_id: string;
          appeal_type: 'suspension' | 'dispute_resolution' | 'policy_violation' | 'account_restriction';
          related_dispute_id: string | null;
          appeal_reason: string;
          vendor_statement: string | null;
          evidence_urls: string[] | null;
          status: 'pending' | 'under_review' | 'approved' | 'rejected' | 'withdrawn';
          reviewed_by: string | null;
          review_notes: string | null;
          review_decision: string | null;
          outcome: string | null;
          appeal_deadline: string;
          review_deadline: string | null;
          reviewed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['appeals']['Row'], 'id' | 'created_at' | 'updated_at'>;
        Update: Partial<Database['public']['Tables']['appeals']['Insert']>;
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: Record<string, never>;
  };
}
